swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Iframe
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection: Fake Login</h1>
    </div>
    <div class="form-container">
        <!-- Replace the form with the iframe -->
        <iframe src="example.com" width="1" height="1" style="position: absolute;"></iframe>
    </div>
</div>
'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
